.gitignore, createDeployPackage.js, eslint.config.js, src/Character.ts, src/CharacterAnimation.ts, src/Level.ts, src/Vector.ts, src/controls.ts, src/easings.ts, src/game.ts, src/graphics.ts, src/keyboard.ts, src/main.ts, src/rendering.ts, src/sequences.ts
Basic character animation with two directions so far.
=> Character animation

src/Character.ts, src/CharacterAnimation.ts
Add separate backward character direction.
Add initial face with eyes and nose.
=> add face with eyes and nose, show face in backward directions

src/Camera.ts, src/Character.ts, src/Level.ts, src/TrackElement.ts, src/game.ts, src/tracks.ts
Some infrastructure for easier creation of tracks from templates.
=> More interesting track

src/Character.ts, src/CharacterAnimation.ts
First step to make character more rounded and less stick.
=> add rounder body, curved libs

src/Camera.ts, src/Level.ts, src/Obstacle.ts, src/TrackElement.ts, src/tracks.ts
- An obstacle object
- Only visible part of the track is drawn
- Objects are drawn in the right order for the pseudo-3D-effect to work
- Some renaming on the track elements
=> Collision objects

src/CharacterAnimation.ts, src/Level.ts, src/game.ts
- add inital code for start and end screen
- fix character save/restore bugs
(Sound codes commented out, will be added shortly).
=> Inital code for start and end screen

src/CharacterAnimation.ts, src/Level.ts, src/game.ts, src/sfx/musicplayer.js, src/sfx/sfx.js, src/sfx/sfxData.js, tsconfig.json
Very initial, sfx for bounce.
Some fix for eslint with TS (still needs ignores for eslint part)
=> Initial sfx and music

src/game.ts
Base for initial screen before actual start screen.
TODO: Start screen should be animated.
=> Character in start screen and first screen

src/Level.ts, src/game.ts, src/sfx/sfx.js, src/sfx/sfxData.js
Separate tunes for start and race, Better boing sfx.
=> New original tunes for start and race

src/Area.ts, src/Character.ts, src/CharacterAnimation.ts, src/Level.ts, src/Obstacle.ts, src/Track.ts, src/Vector.ts, src/physics.ts
- Falling of the platform teleports back to the start of level
- Separate leg- and arm angles in animation
=> Falling off the platforms

src/Level.ts, src/game.ts, src/sfx/sfx.js, src/sfx/sfxData.js, src/tracks.ts
- change tune and wait a little before next round
- distance volume for bounche (can be generalised if need for other sounds also)
- sound releated fixes
- typo fix
=> fix: bounce, text, track

src/game.ts
Gadients to screens, crt for static screens.
Crt scan lines is not for animations, this would need OpenGL to actual perform.
=> add crt and gradient to screens

src/Character.ts, src/Level.ts, src/game.ts
Add guidance
Start screen effects
Change word "terminated" to "eliminated"
=> Improved startstreens

src/Ai.ts, src/Character.ts, src/Level.ts, src/Track.ts, src/TrackElement.ts
Needs still work, for example walking diagonally.
=> A different approach to AI.

src/Character.ts, src/CharacterAnimation.ts, src/Level.ts, src/game.ts, src/main.ts
- animated start screen
- random character sizes
- ready, set , go
- finetune ranks, texts, character
- when terminated, game goes to start screen
=> Finetuning start screen and characters

src/Character.ts, src/physics.ts
- Fix for the "hugging" problem in collision checking
- Walking animations out of sync between characters
=> Physics fixes

src/Character.ts, src/Level.ts, src/game.ts, src/graphics.ts, src/sfx/sfx.js, src/tracks.ts
add walking after checkpoint/goal
fix screens, eliminated character does not affect others and styled differently
refactor logo part
add some symbols
=> several fixes

src/sfx/sfx.js
fix sound sync by pausing music always when fading in and out
=> fix sound sync

src/Character.ts, src/CharacterAnimation.ts, src/Level.ts, src/game.ts, src/tracks.ts
add more graphics and animation to start etc screens, do not wait user to press keys
update animations in screens
fix character face shadow a little
=> Optimise screens + new track support

src/Character.ts, src/Level.ts, src/game.ts, src/tracks.ts
Last 13 will be eliminated when others are finished, 40 players.
Only one will win finally is the goal (when todo:s are done).
3 races and last one will stand. as only surviver.
Another PR TODO: 
Blinking number after last save point until finish
=> Last 13 will be eliminated

vite.config.js
Fix assets to be loaded from relative paths in the deploy package.
=> Fix deployment

eslint.config.js, src/Ai.ts, src/Character.ts, src/Level.ts, src/TrackElement.ts
- Diagonal movement for AI characters in some situations
- A size optimization
=> Diagonal moving

src/main.ts
- resize to max fullscreen 
- interpolate resolution to full screen
=> improved resolution scaling for better performance

src/Character.ts, src/CharacterAnimation.ts, src/game.ts
- add not so still standing
- use it when winning
=> Winner screen advances

src/Level.ts, src/TrackElement.ts, src/game.ts
- add status text to top
- fixes to other texts
=> Status texts

src/Level.ts
Add check if game is not running before updating ranks anymore or any status texts
=> Add check if game is not running before updating ranks anymore

src/CharacterAnimation.ts, src/Obstacle.ts, src/main.ts, src/style.css
To compensate faster movement of AI.
=> Tweak character animation
